version = 1

test_patterns = ["*/tests/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dialect = "typescript"
  environment = [
    "browser",
    "nodejs"
  ]
  module_system = "es-modules"
